# Default values for python-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appimage: tahakarachi/python-app:v3

dbimage: tahakarachi/python-mysql:v2

ingress:
  enabled: true

replicaCount: 2

service:
  port: 80
  type: NodePort
